[package]
name = "powdr-block-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
powdr-riscv-syscalls = { git = "https://github.com/powdr-labs/powdr" }
powdr-riscv-runtime = { git = "https://github.com/powdr-labs/powdr", features = [
  "std",
] }

sbv = { path = "../../../sbv" }

alloy = "0.3"

[workspace]

[patch.crates-io]
# patched add rkyv support & MSRV 1.77
ruint = { git = "https://github.com/scroll-tech/uint.git", branch = "v1.12.3" }

alloy = { git = "https://github.com/scroll-tech/alloy.git", branch = "v0.3.0" }
alloy-eips = { git = "https://github.com/scroll-tech/alloy.git", branch = "v0.3.0" }

alloy-eip2930 = { git = "https://github.com/scroll-tech/alloy-eips", branch = "v0.1.0" }
alloy-eip7702 = { git = "https://github.com/scroll-tech/alloy-eips", branch = "v0.1.0" }

alloy-core = { git = "https://github.com/scroll-tech/alloy-core", branch = "v0.8.0" }
alloy-primitives = { git = "https://github.com/scroll-tech/alloy-core", branch = "v0.8.0" }
alloy-sol-types = { git = "https://github.com/scroll-tech/alloy-core", branch = "v0.8.0" }
